### PR TITLE
typo - probably written on a case-insensitive filesystem

### PR DESCRIPTION
**Pull request by dwhitney**

### CODE REVIEW

**Comment by Callidon** [comment]
Nice catch. I wrote this late in the evening, so thanks for the fix!

**Comment by dwhitney** [comment]
no problem! I've been playing around with this library. It's great!

D

**Comment by Callidon** [comment]
Thank you! I've finished to implement most of SPARQL query features, so now I can implement the SPARQL 1.1 UPDATE protocol!

**Comment by dwhitney** [comment]
Hey let's do standup over the phone - Neda wanted me to run an errand in
Williamsburg and the coffee shop I'm at is having wireless issues. Call me
when you're ready

D

**Pull request merged**
