### PR TITLE
adds support for custom functions

### PR DESCRIPTION
**Pull request by dwhitney**
Hey, I really needed to add support for custom functions as described in #9, so I went ahead and gave it a shot. I thought as you did that SPARQL.js would need to be forked, but then I discovered that it didn't! You can see some discussion here: https://github.com/RubenVerborgh/SPARQL.js/issues/77

I added an example of how support is added in the `examples` directory, but in a nutshell you pass an optional constructor param to the `PlanBuilder` that looks like this:

```javascript
const customFunctions = {
  'http://example.com#REVERSE': function (a) {
    return cloneLiteral(a, a.value.split("").reverse().join(""))
  }
}
```

and then it can be used in a query like this

```
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>
  PREFIX example: <http://example.com#>
  SELECT ?name ?reversed
  WHERE {
    ?s foaf:name ?name .
    BIND(example:REVERSE(?name) as ?reversed) .
  }
```

I'm not too familiar with the code base, but please take a look and I'm sure I can make any changes you suggest. Thanks!

### CODE REVIEW

**Comment by dwhitney** [comment]
Happy to add documentation once it's approved as well

**Comment by Callidon** [comment]
Oooh nice, I didn't know that you could use `sparql.js` this way.
I just have one question: does it work even if the custom function is called **outside** a bind expression? For example, in a FILTER or HAVING BY clause?

Otherwise, the only minor issue I could found is that you pass your set of custom functions with the `any` type. We could replace that by a dedicated type, but I will handle that part once it's merged into the `master` branch.

**Comment by dwhitney** [comment]
Good question. I'll write some tests and get back to you!

**Comment by dwhitney** [comment]
So the answer to "does this work in `FILTER` and `HAVING`" is yes! I've added some tests for both `FILTER` and `HAVING`, updated the example to show usage for both, and I took a stab at introducing a type for custom functions: https://github.com/Callidon/sparql-engine/blob/a60660a38b5068f40fb62c57e715cf6693dbd138/src/engine/plan-builder.ts#L98

**Comment by Callidon** [comment]
Nice! Everything looks good to me. I will look at some details tomorrow and then merge it into the `master` branch.
Thank you again for this 😃

**Comment by dwhitney** [comment]
Cool - I've added documentation to the README

**Comment by Callidon** [comment]
I've updated a bit the README, compared to what you initially wrote. I think that I will need to properly expose all utility functions related to RDF terms manipulation because the API is not easy to use.
Nonetheless, thank you for your contribution!

**Pull request merged**
