### PR TITLE
Fix #16 - using bound variables for the GRAPH and SERVICE IRI

### LINKED ISSUE #16: When a variable is in a `GRAPH` clause, the bound variables are not used
*NOTE* I have fixed this bug in my fork, but there is a failing test I need to resolve and I have only fixed this for `GRAPH` clauses. This also needs to work in `SERVICE` clauses. I will submit a PR when that work is done.

**Describe the bug**

If you check section 13.3.3 (Restricting Possible GraphIRIs)[https://www.w3.org/TR/sparql11-query/#GraphPattern] it describes and shows an example where a variable is used in a graph clause, like `GRAPH ?ppd`, where `?ppd` is a bound variable. This example won't work in sparql-engine since only named and default graphs are checked for variables.

**To Reproduce**

You can load the data and query from the example mentioned above.

**Expected behavior**

The results described in the section should be produced

### PR DESCRIPTION
**Pull request by dwhitney**
This is described in issue #16. But essentially in the SPARQL 1.1 spec in section 13.3.4, the following query is shown and described, but it does not work in `sparql-engine` because the variable bindings are not checked for the value of `?g`:

```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc:   <http://purl.org/dc/elements/1.1/>

SELECT ?name ?mbox ?date
WHERE
  {  ?g dc:publisher ?name ;
        dc:date ?date .
    GRAPH ?g
      { ?person foaf:name ?name ; foaf:mbox ?mbox }
  }
```

Similarly in the SPARQL 1.1 Federated Query section 4 describes the following query: 

```
PREFIX  void: <http://rdfs.org/ns/void#>
PREFIX  dc:   <http://purl.org/dc/elements/1.1/>
PREFIX  doap: <http://usefulinc.com/ns/doap#> 

SELECT ?service ?projectName
WHERE {
  # Find the service with subject "remote".
  ?p dc:subject ?projectSubject ;
     void:sparqlEndpoint ?service .
     FILTER regex(?projectSubject, "remote")

  # Query that service projects.
  SERVICE ?service {
     ?project  doap:name ?projectName . } 
}
```

This pull request fixes both both cases and adds test cases to test them. 

Things to note:
* the test case I added to `graph-test.js` uses a different data set (the data set from the SPARQL spec) that the rest of the tests, so the test case deviates from the pattern of the rest of the test cases in the file. I'm happy to change it with your guidance.
* I'd like to to specifically review how the values are piped through the `Observable`. To check variable bindings, the logic in the `buildIterator` methods were changed to observe the bindings before calling the `_execute` methods. This means that each binding is chunked through an item at a time and I'm somewhat worried that it'll be a performance bottleneck. Maybe you know a better way? Here's specifically the variable I'm worried about: https://github.com/dwhitney/sparql-engine/blob/master/src/engine/executors/graph-executor.ts#L80

Let me know of anything you'd like changed. Thanks!

### CODE REVIEW

**Comment by Callidon** [comment]
Hi,

Thank you for the fix. There is so much tiny point of details in the SPARQL specs that I'm surprised to have missed.

However, as you suspected, the line you highlighted (https://github.com/dwhitney/sparql-engine/blob/master/src/engine/executors/graph-executor.ts#L80) is killing all the pipelining in the approach. In consequence, this will consequently deteriorate the performance of more advanced join algorithms (Bound join and Symmetric hash join) used in the other part of the engine.
You need to change it to preserve the pipelining approach followed initially by GraphExecutor._buildIterator.

**Comment by Callidon** [comment]
After thinking much about it, I think you cannot use a pipelining approach to handle such case, as the Graph variable can be bound differently for each set fo bindings produced.
So, I think my strategy from the previous comment is the way to go.

1. Before buliding the actual iterator for the evaluation, determeine if the bindings produced by the source iterator can bound the graph variable
2. If yes, use your technique
3. Otherwise, use the default evaluation mecanism, with the pipelining approach

**Comment by dwhitney** [comment]
Yeah that sounds good. I'm not sure how to get the scoped variable names, but I can probably figure it out. I'll let you know if I have any questions

**Comment by Callidon** [comment]
Nice! Maybe try to "peek" on the input source to get an idea of the bindings shape or just pass down the information you need from the `PlanBuilder`.

**Comment by dwhitney** [comment]
The "peek" method is what I've got in there now (unless you know a better
way). I have begun to pass scoped variables down from the `PlanBuilder` and
got a basic implementation compiling yesterday, but it was late at night
and I got a bit confused, so I stopped. I'll probably take a look later
this week, but now that I have the basic issue resolved in my fork, I've
got to finish something up for work before I complete it

D

**Comment by dwhitney** [comment]
this is resolved in the latest version!

**Pull request closed without merging**
